# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UUsrsNJd1fmWA/UEXHpzCU4Kgpoccr/D,iv:2jKFYiyDZPs4MUJnpZssQDYa6mOii0X+PfZTS5oChN0=,tag:dEs7AN50GfPxbL7FwDqwXA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:3gJIM8xYFWR8vFo8A1etJfLI4pCFXibslg0qTxLzbZ6JM/lpDw==,iv:BhRyp+UpQiwTObPvegHMO+7ImMEGUcc8wY2bxywV958=,tag:IOkWLB2k4fMQjlChrQaNUw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:F+gIJ5TmYq3np/M=,iv:KDwELP5nubT2e+MfjNI3Dx8U8xdd8E6UNZl6lcMasdE=,tag:uxt3bJm1NQDZiRVZFoQW3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f6yemrallx6x2te9zzeqsr27rjj40pvnc6zh3mwxvr996hq3uuqfu0n6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ2hwYUtPQ2hRQ1AvczJv
            aW1PSEhEYll0WHBoMTdOM09YRU1lSFZ2bVQ0ClpGancrd05Hang1QzZHWm15SC9W
            NVB2NDVDT1JtR2N1bmlORUlsZUlmcDQKLS0tIHg2bXg0WUhxRVFKWWZzbVRHOFR0
            NzY3MmlhNTRtRXJLdFZyYVJCdWNUeDQKvT0OxZ2eMGWpEj0Uy9DwrLfisbYj156F
            RclgqyfH35Ntage2g9/uB2PpRUXvIpgs4FKpKAX/WZ/WPd1CNRuZog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-17T13:31:04Z"
    mac: ENC[AES256_GCM,data:5Rh+IGxlvDlROTpMkPXPxMVxHmnGufP5umfX0yzl5qTui4ftNuL49sk1GRXbTOJQd7qNRK18lPzsw2cSiNekB4KUfSMfz6Nc3UBMwzcAsUIsB+m9Xumnu+bv5eX5G2xJ4+RPe13vL/GtzK459WLR1NcCkezmY9B/7GcCVHny8Vk=,iv:ExK9lHf64PkJFKC7L4TE0KtXPSCRdHEHnrDwz2Bz7ug=,tag:zQrOZ8cSQA4FO+M5hM4j/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
