# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:dVIzBO4eh+EdXduCnhXYDITTw8gc+TOH,iv:SavbaMnBCkOW3whknm6lqk4MdlTglyQUfPw7mewyVYg=,tag:THcpoDsOSnBtPK+2TqlBqQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:07F3VCx8lLbI7IM+8KnC9s8/GmA7EQ6JqOaGYLJwe8PgEg2HhQ==,iv:9z5u0iWHXTvhActgLdhqVjZfslemaPr3Fz+YHxs1reE=,tag:kMHSodMs3qPNQN8SoFOusA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:L0cTG4uwXIzuhWE=,iv:lccagvT6RrBMdyUbkwSZ+giabGz+XtoywaiY1FXx0kA=,tag:/S7zYIJpWkKA11me5nSWug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f6yemrallx6x2te9zzeqsr27rjj40pvnc6zh3mwxvr996hq3uuqfu0n6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNHFLd0hvMEtGczRWZGNH
            QTkvVnFXSmZsbjVGSGROUmlVZjdIdVRTUG04CkFPMDhDYzM4ZU9tRFdnNElHNkZJ
            WEhZeDVVRHRSbWsvZjMyTnpaaG5uQWsKLS0tIG50TGVBVnN2Z3JMcnRTMjRRQzRW
            VTJkOWtEVGpObGdNaUZHSFF4WU5hVG8Ki4x6hFuNmnjuKlhk1TK/S/RwiP8OrfXp
            Qsv6vqVaGZGi33qjm1CcfKzvxIC7+ixV8x69Bf8xBxYqziHiFLCMGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-17T12:33:55Z"
    mac: ENC[AES256_GCM,data:rw7+i1xqkbjIlUw/zbCzLGdo0XtEnWvIi88tCrAQ+NN9zqyYMD9SMOBJMiZmH4C64t6IkliLFdYVqAy++RFEIHqUDFXuLEqU7RtX/FlZjzI8wOFbvYGNQwUnpG20A0laoOScvxzPTFAz+bVqPeu2dl95lPFIBXdMjcHRye/GbRc=,iv:ajQLa+Sj3pc8QdJ1sLsm3RqzhjpyZhRkgrlhtRzSk7A=,tag:UROGI291UKSXwwVhwAWi8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
