---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  namespace: media
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.10
    path: /media
  persistentVolumeReclaimPolicy: Retain
