# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:IOl00Wco4sGkRdhfvHcIgvXQR5ot2lizqzDGCBIOZto11LDJYw==,iv:Ax2PQyUWTrrhCvdrs+QQ37yRgI8aksqR+moqvRlGTAw=,tag:IjpSAFDzribwTYM6pIAZ5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f6yemrallx6x2te9zzeqsr27rjj40pvnc6zh3mwxvr996hq3uuqfu0n6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncTdOUVRuMmJXeExTSDdF
            Nk1PdXpCdEJ6K081djNPQ0Y4TWUzUk9NODJjCmJxbTc1Z0JrbzA1RFNrdFhneTdh
            TllsSUw0endyTG45Wk9WUG8vVzJLQ3MKLS0tIExCbTZWQTRXNnFBbDVNOEFRaVlL
            Q0Q5UU5KcFdFNzVjTVdZQkw1MWpTS2sKtYT8e8DlYUT2mlTA7cZrYJiigLnzJzV9
            tuS1VywuTbbN8Xd7x04At69ElVR1EL/Bv1s48fL2li/ZS0muaoxGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-17T12:33:55Z"
    mac: ENC[AES256_GCM,data:St3trOHj5QAA6AwEFs6/3LjbTzSJdGFRj97J+IVN5CUQFX89Aeu1PHB6ecSHbej8QPWCY62VonI+cP1S/T0ZSXDCjY8Cjd0NBLfDZWZo4Z6mySqG2/ak0gjetOynugS+y0wqAK7uYXHGYQbUelR3aALqRDTd+0PRQqkrp+WGR4o=,iv:VLCkxgIfarj8vueiED6vYYcnIF97qxYjJ85HAY1+jFk=,tag:Ulpyrvs9//nS5oBITWqQBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
