# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:mhD4itT6dyHuizygcNxYXuBt2BMNBeuW/JyHeE7VKj365leSVg==,iv:wYMm3tL1Z12PknmwGFK1EUh8935hnPnNPYn1w6HEWMU=,tag:BVMZ9fdt3eO7wbMXHtQRTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f6yemrallx6x2te9zzeqsr27rjj40pvnc6zh3mwxvr996hq3uuqfu0n6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZHVndnd4UzVlTUYrZzkr
            K2h0Y2pJRittV1IzY1REQlZySUYyMDhlZEh3CnpOdjZIS2lzeFNRaGRVcXcxT3Fk
            YTQ4UE1pTG5LcEp0blVyUGJZTTZyakkKLS0tIEN6aUV0bFlZM3h0S2tnZ2NNUkZQ
            QUZTYituMmxQc0dTUDRKeVNLUXRmQVEKohwGoKIh5dIh2oWih6/wi2TYmJxy9r68
            hUkQqbN+bd6TS33G88zOsj/p/W8tvB1thsGKj6sFACObRz7OXpPe+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-17T13:31:04Z"
    mac: ENC[AES256_GCM,data:tqQq/2Hh+o4BI0dC66eY/F+P5V0bWpPVLmx+ruzg8d1Q4LxwGGVF5gpGL81aySaCNZeV3UPqnHedY26NhLsq0Uxkfj8YOmXgPJaS9j3OAV7f4L3hPvysdMUeyDgqS1fXvbw+X+HzwwFTUMANs1nqwNeX7IQ+BFQVyLQM8zqddjs=,iv:fG+L07wvnpuY6kuK9e1Y/0AaqIEss3QGFFHMjzBLAJ0=,tag:cr/Qfm/fNMgMeGPuv3Tfug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
