# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:ndlM6gp5N2fpZUZGZ+9RjWh/jwWzouZp,iv:stwDeGTwp2Q6knvqnmyyQdW29PzHjvIRqNw2R8yrwbc=,tag:KYg+20AeYPbse4Tf7ZwkWQ==,type:str]
    api-key: ENC[AES256_GCM,data:5Y2QyKTc2+/cNcNlKMQrdgwymp0m0IW75LSJVlRpG0rl7UUEpQ==,iv:nRpeUoY9QwwwPaE5fV4TGb+0tDfZdXxda+wPMV2gupg=,tag:JhJnie11r+u51JH3d9xYGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f6yemrallx6x2te9zzeqsr27rjj40pvnc6zh3mwxvr996hq3uuqfu0n6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVZMdGk2YnB3MVVYYUZn
            S0U0THBheE5icEtCWlZLcXV1NWFrend3VG5VCms3OFAxZXVxWjAzNmIxZVVTVUVy
            Ukc2WmZ6akFrNzVJMEFiNWFuRktXTlkKLS0tIExlOTdabDhlZGRaVGY2TFZOT3hl
            M2M0RDFiVWRGMEQ5MTFEWFB5VGUweEkKjY2aYGbiPQ6uTDK94Ux1bo4FSAfu7HMl
            sdRxYjznbH6WmAJDZSf62mTN0mr0oMkCRmxAt/G+TQyXe97Q9XVjJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T20:14:51Z"
    mac: ENC[AES256_GCM,data:0HPs218qiF5t/nh7+eC70S5+At2olkPY4rg15FRmCUzXoCq35DEHQg+Eg4MT1r+EuuPx7YVCWzypng0LGHG5loJpe2pdP7osZePm4cc1RDIL5seuHLmRdB9t8Q2MSyBd/WkL22mvNqruoRhRw4MFx+d/hexmSSkJIOrVyadKK7w=,iv:jzOjKaM5TnG1AR6CKRJoZ5q5MK6ti7xFLUzAkE6Z2NA=,tag:ABc2cPqu/RYHSfye8mQPUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
