# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ky1V8gXbv4Uojw==,iv:zU84AGa4ztNEXvTeAJDoD9cGnNigbijyAbphs8Xsb3E=,tag:UzMWtzEqXdPqoIfgsCFfLQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YMfPpproRu3jtKbXBhCgfUjD3QmjZ0FA,iv:Tb3JpL4zDYoYNKfuCsUh1dgAwhzUTo3PMvjBiOGJPLI=,tag:DlF9RT4J1u//AXNkamIvIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15f6yemrallx6x2te9zzeqsr27rjj40pvnc6zh3mwxvr996hq3uuqfu0n6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxajlWYWZTelBacko3WGdY
            MGRCS1FCMzFwT0pBcDVxY2Y3UkczM3NWUHprCnB3b2hVV2U0bXc3d0cvenVaRVBi
            dnk3NFNncGFMbUozTFNBdEF2NnhyTDAKLS0tIFp2cWxIbTc0VGRESFFpWWdQS21y
            UU51QWREeDRscm5zT1hxbDFZYW1Od2sKUa1ikz3QS675GIkS66x+H9vNjmYcpwba
            ajbLiKUlFPCD1X3fBS/8cl0vJ5IaQHoAn44lQZpHwLxTXLVIleSlCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-08T20:14:51Z"
    mac: ENC[AES256_GCM,data:c8vpMxLzWyhquFv6/O99DGczy9DLGuym+gl+bH7NSovFoS1N93VVgFRg16VZ0eybVoWHyiejesRNuWsbP6M8t/DlhKF5ne/VP7O1c6TWOs+Xh8IoS0b/pEjZNPd5EGsHPr+i/8Psn06JZdbtMWGhbQuxyl36Fq4oFT+P5UAgh1U=,iv:R4VDMjtCnP6pVQX9fNZaSerjoepa6wA9LzgeOWHDc1I=,tag:Tw4ayth7lxq3rTlUehJY+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
